<?php

/**
 * @file
 * Primary module hooks for read_pricing module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 */
function read_pricing_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'read_pricing/read_pricing';
  $attachments['#attached']['library'][] = 'jquery_ui_effects/blind';
}

/**
 * Implements hook_theme().
 */
function read_pricing_theme() {
  return [
    'price_list_family' => [
      'variables' => ['foo' => NULL],
    ],
    'price_list_education' => [
      'variables' => ['foo' => NULL],
    ],
    'price_list_homeschooler' => [
      'variables' => ['foo' => NULL],
    ],    
    'price_list_business' => [
      'variables' => ['foo' => NULL],
    ],
    'price_list_lib' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for price_list_family template.
 *
 * Default template: price_list_family.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_price_list_family(array &$variables) {
  $variables['foo'] = 'bar';
}

function template_preprocess_price_list_education(array &$variables) {
  $variables['foo'] = 'bar';
}

function template_preprocess_price_list_homeschooler(array &$variables) {
  $variables['foo'] = 'bar';
}

function template_preprocess_price_list_business(array &$variables) {
  $variables['foo'] = 'bar';
}
