<?php

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function mnet_admin_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'node_deal_form' || 'node_deal_edit_form') {
    $form['#attached']['library'][] = 'mnet_admin/nodelib';
  }
  
}

/**
 * Implements hook_options_list_alter().
 */
function mnet_admin_options_list_alter(array &$options, array $context) {
  if ($context['fieldDefinition']->getName() === 'field_category') {
    $options['_none'] = t('Select a category');
  }
  if ($context['fieldDefinition']->getName() === 'field_user_region') {
    $options['_none'] = t('Select region');
  }
}


/**
* Implements hook_form_FORM_ID_alter().
*
* Disable the required 'Alternative text' field in the CKEditor's image dialog.
*/
function mnet_admin_form_editor_image_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['attributes']['alt']['#required'] = FALSE;
}

